############################################################
# Application
############################################################

spring.application.name=spring-unified-core

# \uAE30\uBCF8 \uC2E4\uD589 \uD504\uB85C\uD30C\uC77C
spring.profiles.active=local


############################################################
# JPA \uACF5\uD1B5 \uC124\uC815
############################################################

# OSIV \uBE44\uD65C\uC131\uD654
# \uD2B8\uB79C\uC7AD\uC158 \uBC16\uC5D0\uC11C Lazy \uB85C\uB529\uC744 \uB9C9\uC544 \uC131\uB2A5 \uBB38\uC81C \uC608\uBC29
spring.jpa.open-in-view=false


############################################################
# MyBatis \uACF5\uD1B5 \uC124\uC815
############################################################

# MyBatis Mapper XML \uC704\uCE58
mybatis.mapper-locations=classpath:/mapper/*.xml

# type alias \uD328\uD0A4\uC9C0
mybatis.type-aliases-package=com.example.demo

# DB snake_case -> Java camelCase \uC790\uB3D9 \uBCC0\uD658
mybatis.configuration.map-underscore-to-camel-case=true


############################################################
# Logging \uAE30\uBCF8 \uB808\uBCA8
############################################################

# root \uB85C\uADF8 \uB808\uBCA8
logging.level.root=info


############################################################
# Swagger \uC124\uC815
############################################################

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# =========================
# \uD504\uB85C\uD30C\uC77C \uC124\uC815 local/s3
# =========================
file.storage.type=s3

############################################################
# \uD30C\uC77C \uC124\uC815
############################################################

file.upload-dir=E:/myplayground/upload/
file.allowed-extensions=jpg,jpeg,png,pdf,txt
# \uD30C\uC77C 1\uAC1C \uCD5C\uB300 \uD06C\uAE30
spring.servlet.multipart.max-file-size=50MB
# \uC804\uCCB4 \uC694\uCCAD \uD06C\uAE30 (\uBA40\uD2F0 \uC5C5\uB85C\uB4DC \uD569\uACC4)
spring.servlet.multipart.max-request-size=100MB
# \uD30C\uC77C\uC0AD\uC81C \uAE30\uC900\uC77C
file.cleanup.days=7


############################################################
# Access/Refresh Token \uC124\uC815
############################################################

# \uAC1C\uBC1C:false, \uC6B4\uC601: true
app.cookie.secure=false
# SPA + cross domain
app.cookie.same-site=None
app.cookie.domain=.company.com   

# Access Token (30\uBD84)
app.auth.access-expire-seconds=1800
# Refresh Token \uB9CC\uB8CC (\uCD08), 1209600 = 14\uC77C
app.auth.refresh-expire-seconds=1209600


# =========================
# AWS S3 \uC124\uC815
# =========================
aws.s3.bucket=demo-files-571741813439-ap-northeast-2-an
aws.s3.region=ap-northeast-2

# =========================
# AWS \uC778\uC99D \uC815\uBCF4
# =========================




############################################################
# \uAD8C\uD55C \uCCB4\uD06C \uC0AC\uC6A9 \uC5EC\uBD80
############################################################

app.auth.enabled=false



